"""your message here

Revision ID: 11b9bf9f26a9
Revises: 4ee341d8e351
Create Date: 2025-05-15 23:36:21.754978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b9bf9f26a9'
down_revision: Union[str, None] = '4ee341d8e351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workout_exercise_workout_id_fkey', 'workout_exercise', type_='foreignkey')
    op.create_foreign_key(None, 'workout_exercise', 'workout', ['workout_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_exercise', type_='foreignkey')
    op.create_foreign_key('workout_exercise_workout_id_fkey', 'workout_exercise', 'workout', ['workout_id'], ['id'])
    # ### end Alembic commands ###
