"""exercise_model_update

Revision ID: 212213722339
Revises: f23882303c5f
Create Date: 2025-05-11 23:31:11.278524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212213722339'
down_revision: Union[str, None] = 'f23882303c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('exercise', sa.Column('intensity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'intensity')
    op.drop_column('exercise', 'duration')
    # ### end Alembic commands ###
