"""change session table to workout plan

Revision ID: 4d9a54e76be3
Revises: 8ec72060875c
Create Date: 2025-05-16 11:18:01.478448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d9a54e76be3'
down_revision: Union[str, None] = '8ec72060875c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_plan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('session')
    op.add_column('workout_exercise', sa.Column('workout_plan_id', sa.BigInteger(), nullable=True))
    op.alter_column('workout_exercise', 'workout_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_foreign_key(None, 'workout_exercise', 'workout_plan', ['workout_plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_exercise', type_='foreignkey')
    op.alter_column('workout_exercise', 'workout_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('workout_exercise', 'workout_plan_id')
    op.create_table('session',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name='session_workout_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='session_pkey')
    )
    op.drop_table('workout_plan')
    # ### end Alembic commands ###
