"""workout model changes 2

Revision ID: 8ec72060875c
Revises: e748f3da78d2
Create Date: 2025-05-15 23:59:27.191441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ec72060875c'
down_revision: Union[str, None] = 'e748f3da78d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('workout', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('workout', 'created_at')
    # ### end Alembic commands ###
