"""workout model changes

Revision ID: e748f3da78d2
Revises: 11b9bf9f26a9
Create Date: 2025-05-15 23:47:28.790049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e748f3da78d2'
down_revision: Union[str, None] = '11b9bf9f26a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('workout', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('workout', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('workout', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('workout', 'notes')
    op.drop_column('workout', 'ended_at')
    op.drop_column('workout', 'started_at')
    # ### end Alembic commands ###
