# Generated by Django 5.2 on 2025-04-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Duration', models.IntegerField()),
                ('Intensity', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
