# Generated by Django 5.2 on 2025-05-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialAccount',
            new_name='Social',
        ),
    ]
