# Generated by Django 5.2 on 2025-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Goal', models.CharField(max_length=100)),
                ('Exercise_Count', models.IntegerField()),
                ('Duration', models.DurationField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Notes', models.TextField(blank=True)),
            ],
        ),
    ]
